### ISSUE TITLE
Mamba install fails

### ISSUE THREAD

**Issue by mturoci** [amauryval/publish_conda_package_action#4]
I am trying the latest, `2.0.3` version of this gh action, but getting.

```sh
   > [3/5] RUN mamba install -y -c conda-forge anaconda-client conda-build conda-verify numpy boa=0.11.0:
  0.537   File "/opt/conda/bin/mamba", line 7, in <module>
  0.537     from mamba.mamba import main
  0.537   File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
  0.537     import libmambapy as api
  0.537   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
  0.537     raise e
  0.537   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
  0.537     from libmambapy.bindings import *  # noqa: F401,F403
  0.537     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  0.537 ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

My configuration:

```yml
- name: Publish to Conda
  uses: amauryval/publish_conda_package_action@2.0.3
  with:
    CondaDir: 'py/h2o_wave/conda'
    Platforms: 'noarch'
    CondaUsername: ${{ secrets.CONDA_USERNAME }}
    CondaPassword: ${{ secrets.CONDA_PASSWORD }}
  env:
    # VERSION clashes with conda build. Use PKG_VERSION instead.
    PKG_VERSION: ${{ env.VERSION }}
```
